version: 2.1
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker File
          command: |
            docker compose -f docker-compose-build.yaml build --parallel
      - run: 
          name: Docker images
          command: |
            docker images
      - run: 
          name: Tag Docker Image
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            docker tag udagram-api-feed $DOCKERHUB_USERNAME/udagram-api-feed:$TAG 
            docker tag udagram-api-user $DOCKERHUB_USERNAME/udagram-api-user:$TAG 
            docker tag reverseproxy $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG 
            docker tag udagram-frontend:local $DOCKERHUB_USERNAME/udagram-frontend:$TAG 
      - run:
          name: Push application Docker image
          command: |
            TAG=v1.$CIRCLE_BUILD_NUM
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/udagram-api-feed:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-api-user:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-reverseproxy:$TAG
            docker push $DOCKERHUB_USERNAME/udagram-frontend:$TAG

workflows:
  build: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
