apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: hoangminh173259/udagram-reverseproxy:v1.3
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        volumeMounts:
        - name: secret-volume
          mountPath: "/root/.aws"
          readOnly: true
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
            cpu: "500m"
          requests:
            memory: 1024Mi
            cpu: "300m"
      # restartPolicy: Always
      volumes: 
      - name: secret-volume
        secret: 
          secretName: aws-secret
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3

      
