apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacity-frontend
  name: udacity-frontend
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udacity-frontend
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 80
  selector:
    app: udacity-frontend
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
