apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: hoangminh173259/udagram-api-user:v1.3
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        volumeMounts:
        - name: secret-volume
          mountPath: "/root/.aws"
          readOnly: true
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 2048Mi
            cpu: "1"
          requests:
            memory: 1024Mi
            cpu: "0.5"
      restartPolicy: Always
      volumes: 
      - name: secret-volume
        secret: 
          secretName: aws-secret
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 3
        #   periodSeconds: 3

      
